apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-b.fullname" . }}
  labels:
    app: {{ include "service-b.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "service-b.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "service-b.name" . }}
    spec:
      containers:
        - name: service-b
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.app.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.app.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
